" Extend rather than replace Vim 8 defaults
source $VIMRUNTIME/defaults.vim

" Overrides for Git for Windows
set clipboard& wildmode& laststatus& statusline&

" Main options
set hidden
set showmatch hlsearch shortmess-=S
set spell spellcapcheck= complete+=k
set backspace=indent
set autoindent shiftwidth=0 tabstop=4
set ignorecase wildignorecase smartcase
set splitbelow splitright
set number cursorline
set linebreak breakindent showbreak=↳\ \ \ "
set colorcolumn=+1
set printoptions=formfeed:y

" Background detection fails in Windows Terminal
set background=dark

" Windows Terminal doesn't support undercurl, so fallback to underline
set t_Cs=

" Better mouse support
set ttymouse=sgr mouse=a

" More GUI-like behavior
set title belloff=all lazyredraw

" Improve responsiveness and disable swap files (DANGEROUS)
set updatetime=100 noswapfile

" Continuous pane boundary
set fillchars+=vert:│

" Mode-dependent cursor shape
set t_SI=[5\ q t_SR=[3\ q t_EI=[1\ q
autocmd VimLeave * set t_me=[0\ q

" Why isn't this default
nnoremap Y y$

" Shift-less command mode
noremap ; :
tnoremap ; :

" Quick save file without messing up timestamp
nnoremap <silent> , :<C-u>update<CR>

" Quick hide search result highlighting
nnoremap <silent> <BS> :<C-u>noh<CR>

" Speedy buffer switching
nnoremap <Space> <C-^>

" Show buffer menu and prompt
nnoremap <silent> <Leader>b :<C-u>Buffers<CR>

" FZF in the current project (Git repo if present, otherwise whole directory)
nnoremap <expr> <silent> <C-p> FugitiveHead() != '' ? ':<C-u>GFiles<CR>' : ':<C-u>Files<CR>'

" Auto-insert closing bracket for block
inoremap {<CR> {<CR>}<ESC>O

" Insert ASCII underline for headings
nnoremap _ yypVr=o<CR>

" IDE actions
nnoremap <silent> <F2> :<C-u>ALERename<CR>
nnoremap <silent> + :ALECodeAction<CR>
nnoremap <silent> gd :<C-u>ALEGoToDefinition<CR>
nnoremap <silent> gD :<C-u>ALEGoToTypeDefinition<CR>

" GHCi config file is just executable Haskell
autocmd BufNewFile,BufRead .ghci set filetype=haskell

" Use LaTeX distro to print as PDF
command Pdf hardcopy >%.ps | !ps2pdf %.ps<CR>

" Don't need vinegar.vim for this :)
" Also helps to use :Explore rather than :e
let g:netrw_banner = 0

" ALE language server plugin
let g:ale_completion_enabled = 1
let g:ale_fix_on_save = 1

" True-color scheme that matches terminal (One Half Dark)
set termguicolors
let g:one_allow_italics = 1
colorscheme one

" Without undercurl, color must be set manually (this is orange from One Dark)
call one#highlight('SpellBad', 'd19a66', '', '')
call one#highlight('SpellCap', 'd19a66', '', '')
call one#highlight('SpellLocal', 'd19a66', '', '')
call one#highlight('SpellRare', 'd19a66', '', '')
