[env]
TERM = "alacritty-direct"

[window]
resize_increments = true
option_as_alt = "Both"

[scrolling]
history = 0

[font]
size = 14

[font.normal]
family = "PragmataPro Mono"

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true

[cursor.style]
shape = "Beam"
blinking = "On"

[mouse]
hide_when_typing = true
